sudo: required

notifications:
  email: false
  slack:
    if: branch in (main, staging, production)
    on_success: never
    on_failure: always
    on_pull_requests: false
    secure: OX6UmHvOhTK5OgxU1/EP65iTvuggluD9O+mtfqF1PehoDNSP6tsek7BX0jVH/YiL2XbzVrK5XWV/vH2C1dlVtKBCE8OySwMZ76zJPqgj8VXUMHU0IL0pRDZpIizDRUrKBSMCB+sxjA6v6RQDDte9NLYfPJIgqmZsyE6ME4IoFCtKm7LW2T0QoVZZb8a8diPYc5cV20R5v/Q40cnE+aqPsN8C+pZhue1ZAkiKW2btzgJJyUrTxf6QtYN2usvrOfEqk4pfz41re92flhlbEXtwcsOzAfzy8BiWQIegKZHg3YWaP0hSS+ynjm4/P40hkfo7pLqBr17wUf5sN1rHabzYO5fVdzNa5yaYzCC8ILq8iCz/9ijVxEo1k2k8gUjyY6PymgUA6zWCPfpJemiivZ/OUMFufJb/Ab0Wh/zbg68xMt4HghRUuuThK0yaQATUtydjQ6G5Nwq+zWqa/e5jeub+LrnLuS+6hMqMDUuN1eBB1BorVIBQhouhT/NoTTYwLBzDpWTIrgi6Kx74wxqQvZgbrjws80epF23hVcFDqp0WWMIwvx1Kv7wdxdA5r6Q79EP0GdqBcmkGLoOvT/bSITU9MjnFaAFFtfthjY2DwALjFGknqopYcjJQ/xFAHNj/g4cXg5UgTMqaWooechQ+QfQdfG5kjj6mB5HNeteDCcc7C+o=

services:
  - docker

language: go

go:
  - 1.13.1

install:
  - export GOFLAGS=-mod=vendor

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0

script:
  - test -z "$(gofmt -s -l `find . -name "*.go" | egrep -v vendor` | tee /dev/stderr)"
  - golangci-lint run -E gosec
  - ./test.sh

deploy:
  provider: script
  script: run-parts --verbose --exit-on-error --regex '.*sh$' ./run/deploy
  on:
    branch: main

env:
  global:
    secure: "Ag9fEZ0PCWfJ7We8/HoX+L8VtcS1C8R4Lm7xQOasVvLDQNCqsMqpWe+bbJz8wpWkxFTyYWtuM1wN2Se/D4PYY+JUrYDYL6t1cGv1SwUjMUPHmXXFp1d0zX+7lpYh3sCDyTzySPAT7Q3p2P5VfnI+uEVvCfN6pEHRLARDzlJRN6uiFtrsrsG7XurRrPuElIx0cBdj5rMN45jsKMVAkl6ZUpJV2CypeESgl4F5FoC7zab1b45DTl/WHaVORvxOhSpbnrjjffhaPXfFahEqiMrsRtr8fCu12ZomnkiLBcKvl+kwrvYkkP67mfKN7MErL2uv4YrAYmoZalnMJeM0/haEotC4vfSVH1B076EmaAk+qjaaS5apaqlz4/eik2Ti48sjVC3pjRQ2AmVt9yfuaiQgeOTOSd/5q6OjrzNeASKk6Iv48PgGwOetJ4C62Mg+WElG3onwH3QCYRp2JCEB0EfL+icEYRFB9ihkMRomB4EOSC3RPszR2OV3FckejiRnHCa1ZRjYBG2VonUWcjq76z97PWwpWR9tkraZkOebFIB6djjjLqBxAbd8y01VmWn1v2zt2GxZqwXOm83yBwXg21X33L09SSLbf7/lcu3hyQkDFnQ41gKD+Yn5HERl+CnOZiliFtPstyBwb39kyQiYc5Dy0RShtCBc8gBtr5ctO8wcTFA=" # geonetci_api_token
    secure: "Qrwn4DaM8t9Hq7G4+Q/1Fth2Ufi5b+JNdhxhiWuM8Q7G4SgZByyiO1W8DOWH7ZITTOKrsTQbGKQiMfWtHNkaRxfaV7TDKjXUBCp3T3zCswhIkt97RCwp/3rMw/BsPYT73DYzi2zFynk/gnv8yLy1YlWZwNz0XdwemKXZIDUGyIUWm1/afH0niwFfySHDqMtV/0Gckj3UVty6pTM/6UJO4himqAD0EM0kFBsebLr6OOfQBjrjtpYEWHD8VhcVhPVSXOAUpfjPcF0zTzyjZSDdMxaTKud4zIfxqWHpzzwZOzWkxUR5pwRzW9Nx0mrn00QYO3r38m2zFb0ThVQZyQ3jbYcCpRtzfUbILbUiRIuU977PR+ZvkXxG4mITow4TP6tgsMW9DBhTLi6WmNjZ5vifwpc0sAw0Ti/SqTM6oxhQCHpcHGVSuUlbuJKMEpq9pndu/ZqoWjEe9mC4L5co2X8fnY6c8X6Ak+1m6Q93JJ1nR5aqBktlJDllEWWwcCBjbqkYBREzHwa5JvYjY0GpDfJF66ahIt7GErpwnf20xeL+77OyPw41quMPxxc2xb/sZBidxhcz1n2Kb2sMiSIQGMDklawKH+CHLRIdZTil1CjcYnTICU4oY2WDDwH7taAJgzAS3UiL2Wx2Z/VoEKDams9vD0hCWI+V0bxavOKBfmoj2vU=" #TRAVIS_API_TOKEN

# vim: set ts=2 sw=2 tw=0 et:
