---

PreparedBy: "Geodetic Processing Specialist"
PrimaryDatacentre: "data.geonet.org.nz"
URLForMoreInformation: "www.geonet.org.nz"
ExtraNotes: "additional information and pictures could be found\nat http://www.geonet.org.nz/data/types/geodetic"

ContactAgency:
  Agency:    "GNS Science"
  PreferredAbbreviation: "GNS"
  MailingAddress:  "1 Fairway Drive, Avalon 5010,\nPO Box 30-368, Lower Hutt,\nNew Zealand"
  PrimaryContact:
    Name:         "GeoNet reception"
    TelephonePrimary:   "+64 4 570 1444"
    TelephoneSecondary: ""
    Fax:    "+64 4 570 4676"
    Email:        "info@geonet.org.nz"
  SecondaryContact:
    Name:         "Geodetic Processing Specialist"
    TelephonePrimary:   "+64 4 570 1444"
    TelephoneSecondary: ""
    Fax:    ""
    Email:        "info@geonet.org.nz"
  Notes: ""

ResponsibleAgency:
  Agency:    "Land Information New Zealand"
  PreferredAbbreviation: "LINZ"
  MailingAddress:  "155 The Terrace, PO Box 5501, Wellington 6145\nNew Zealand"
  PrimaryContact:
    Name:         "LINZ Reception"
    TelephonePrimary:   "+64 4 460 0110"
    TelephoneSecondary: ""
    Fax:    "+64 4 472 2244"
    Email:        "positionz@linz.govt.nz"
  SecondaryContact:
    Name:         ""
    TelephonePrimary:   ""
    TelephoneSecondary: ""
    Fax:    ""
    Email:        ""
  Notes: "CGPS site is part of the LINZ PositioNZ Network http://www.linz.govt.nz/positionz"

# used to determine country name
Countries:
  New Zealand:
    Latitude: -40.0
    Longitude: 174.0
  New Zealand:
    Latitude: -29.0
    Longitude: -178.0
  Tonga:
    Latitude: -21.2
    Longitude: -175.2
  Samoa:
    Latitude: -13.8
    Longitude: -172.1
  Niue:
    Latitude: -19.0
    Longitude: -169.9
  Antarctica:
    Latitude: -77.8
    Longitude: -166.7

# https://files.igs.org/pub/station/general/antenna.gra
Diagrams:
  AOAD/M_T: |2+
                               -----
                           /           \
                          |             |
        +-------------------------------------------------+     <--  0.1020  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0380
      +-------------------+-------------+-------------------+   <--  0.0350  BCR
                          |             |
                         =|             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             RXC=NRP
      <--                      0.3810                     -->
  ASH701945B_M: |2+
                             +-------+
                           /           \
                          |             |
        +-----------------+-------------+-----------------+     <--  0.1006  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0376
      +-------------------+-------------+-------------------+   <--  0.0346  BCR
                          |             |
                          |             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
      <--                      0.3794                     -->
  ASH700936B_M: |2+
                               -----
                           /           \
                          |             |
        +-------------------------------------------------+     <--  0.1020  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0380
      +-------------------+-------------+-------------------+   <--  0.0350  BCR
                          |             |
                         =|             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
      <--                      0.3810                     -->
  ASH700936C_M: |2+
                               -----
                           /           \
                          |             |
        +-------------------------------------------------+     <--  0.1020  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0380
      +-------------------+-------------+-------------------+   <--  0.0350  BCR
                          |             |
                         =|             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
      <--                      0.3810                     -->
  ASH700936D_M: |2+
                               -----
                           /           \
                          |             |
        +-------------------------------------------------+     <--  0.1020  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0380
      +-------------------+-------------+-------------------+   <--  0.0350  BCR
                          |             |
                         =|             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
      <--                      0.3810                     -->
  ASH700936E: |2+
                            +---------+
                           /           \
                          |             |
        +-----------------+-------------+-----------------+     <--  0.1008  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0378
      +-------------------+-------------+-------------------+   <--  0.0348  BCR
                          |             |
                          |             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
      <--                      0.3794                     -->
  ASH701933C_M: |2+
                            +---------+
                           /           \
                          |             |
        +-----------------+-------------+-----------------+     <--  0.1008  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0378
      +-------------------+-------------+-------------------+   <--  0.0348  BCR
                          |             |
                          |             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
      <--                      0.3794                     -->
  ASH701945E_M: |2+
                             +-------+
                           /           \
                          |             |
        +-----------------+-------------+-----------------+     <--  0.1006  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0376
      +-------------------+-------------+-------------------+   <--  0.0346  BCR
                          |             |
                          |             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
      <--                      0.3794                     -->
  LEIAT504: |2+
                             +-------+                          <--  0.1393
                           /           \
                          |             |
        +-----------------+-------------+-----------------+     <--  0.1012  TCR
        |                                                 |
        |                                                 |
        |                                                 |
        |                                                 |
      +-+-------------------------------------------------+-+   <--  0.0378
      +-------------------+-------------+-------------------+   <--  0.0345  BCR
                          |             |
                          |             |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
      <--                      0.3794                     -->
  SEPCHOKE_B3E6   SPKE: |2+
                                 |                               <--  0.3977
                                 |
                                 |
                                | |
                                | |
                               |   |
                               |   |
                               |   |
                             ---------                           <--  0.2847
                            /         \
                           /           \
                          /             \
                         /               \
                        /                 \
                       /                   \
                      /                     \
                     /                       \
                    /                         \
                   /                           \
                  /                             \
                 /                               \
                /                                 \
               /                                   \
              /                                     \
             /                                       \
            /                                         \
           /                                           \
          /                                             \
         /                                               \
        /                                                 \
       /                                                   \
      /                   ---------------                   \    <--  0.1550
     /                  /                 \                  \   <--  0.128  
     |                 |                   |                 |
     |+-----------------------------------------------------+|   <--  0.1080  TCR
     ||                                                     ||
     ||                                                     ||
     ||                                                     ||
     ||                                                     ||
     ++-----------------+-----------------+-----------------++   <--  0.0480  BCR
                        |                 |
                        |                 |
                        |                 |
                        +--------x--------+                      <--  0.0000  BPA=ARP
                        <--    0.1210   -->
      <--                      0.3630                     -->
     <---                      0.3734                     --->
  TRM22020.00+GP: |2+
                             ----^----
                          /             \
      ++----------------+-----------------+----------------++   <--  0.0591  TGP
      ++---------------+-------------------+---------------++   <--  0.0556  BGP
                       |                   |
                        |                 |
                         |               |
                          +------x------+                       <--  0.0000  BPA=ARP
                                                                             NOM=NRP
       <--                     0.4668                    -->                 Notches
      <--                      0.4826                     -->                Edge
  TRM29659.00: |2+

                             -----
                         /           \
                        |             |
      +-------------------------------------------------+     <--  0.1020  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0381
    +-------------------+-------------+-------------------+   <--  0.0350  BCR
                        |             |
                       =|             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           RXC=NRP
    <--                      0.3810                     -->
  TRM33429.20+GP: |2+
                             ----^----
                          /             \
      ++----------------+-----------------+----------------++   <--  0.0631  TGP
      ++---------------+-------------------+---------------++   <--  0.0596  BGP
                       |                   |
                       |                   |
                        |                 |
                         +-------x-------+                      <--  0.0000  BPA=ARP
                                                                             NOM=NRP
       <--                     0.4668                    -->                 Notches
      <--                      0.4826                     -->                Edge
  TRM41249.00: |2+
       / --------------------------------------------- \
      +                                                 +
       \ --------------------------------------------- /
                       \               /
                        \             /
                         \-----x-----/                        <--  0.0000  BAM=ARP
                                                                           RXC=NRP
      <--                    0.3396                   -->                  Notches
  TRM57971.00: |2+
  
       / --------------------------------------------- \
      +                                                 +
       \ --------------------------------------------- /
                       \               /
                        \             /
                         \-----x-----/                        <--  0.0000  BAM=ARP
                                                                           RXC=NRP
      <--                    0.3396                   -->                  Notches
  TRM55971.00: |2+
       / --------------------------------------------- \
      +                                                 +
       \ --------------------------------------------- /
                       \               /
                        \             /
                         \-----x-----/                        <--  0.0000  BAM=ARP
                                                                           RXC=NRP
      <--                    0.3396                   -->                  Notches
  TRM115000.00: |2+
      / --------------------------------------------- \
     +                                                 +
      \ --------------------------------------------- /
                      \               /
                       \             /
                        \-----x-----/                        <--  0.0000  BAM=ARP
                                                                          RXC=NRP
     <--                    0.3396                   -->                  Notches
  TRM115000.10: |2+
      / --------------------------------------------- \
     +                                                 +
      \ --------------------------------------------- /
                      \               /
                       \             /
                        \-----x-----/                        <--  0.0000  BAM=ARP
                                                                          RXC=NRP
     <--                    0.3396                   -->                  Notches
#vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
